<a href="https://colab.research.google.com/github/vinisouz4/TensorFlowStudy/blob/main/ClassificacaoRegressao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import tensorflow as tf
import numpy as np

In [78]:
tf.compat.v1.disable_eager_execution()

In [79]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [80]:
y = np.array([[0.0], [1.0], [1.0], [1.0]])
y

array([[0.],
       [1.],
       [1.],
       [1.]])

In [81]:
W = tf.Variable(tf.zeros([2,1], dtype=tf.float64))

In [82]:
W

<tf.Variable 'Variable_2:0' shape=(2, 1) dtype=float64>

In [83]:
# Criando funcao de ativacao
 # Ele me retorna true ou false, quando o numero de x for maior que o numero y, caso nao ele me retorna false
def step(x):
  return tf.compat.v1.cast(tf.compat.v1.math.greater_equal(x, 1), tf.float64)

In [84]:
#Convertendo o X para uma constante
X = tf.constant(X, dtype=tf.float64)

In [85]:
init = tf.compat.v1.global_variables_initializer()

In [86]:
camada_saida = tf.matmul(X, W)

In [87]:
camada_saida_ativacao = step(camada_saida)

In [88]:
# Calcular o erro:
erro = tf.subtract(y, camada_saida_ativacao)

In [89]:
# Criar o delta:
delta = tf.compat.v1.matmul(X, erro, transpose_a=True) # Ele vai realizar o transpose da matriz A no caso da variavel X para conseguir realizar o calculo do delta

In [90]:
treinamento = tf.compat.v1.assign(W, tf.add(W, tf.multiply(delta, 0.1))) # Aqui ele vai calcular os pesos para o peso ideal da minha rede neural, o assign realiza isso
# O 0.1 é a taxa de aprendizagem que pode ser alterado

In [91]:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida))
    print("\n")
    print(sess.run(camada_saida_ativacao))
    print("\n")
    print(sess.run(erro))

[[0.]
 [0.]
 [0.]
 [0.]]


[[0.]
 [0.]
 [0.]
 [0.]]


[[0.]
 [1.]
 [1.]
 [1.]]


print com os dados de redes neurais utilizados

IMG_643.png

In [92]:
# Sessao com ajuste automatico dos pesos:
with tf.compat.v1.Session() as sess:
    sess.run(init)
    epoca = 0
    for i in range(15):
      epoca += 1
      erro_total, _ = sess.run([erro, treinamento])
      erro_soma = tf.compat.v1.reduce_sum(erro_total) # Reduzir ao maximo o numero de erros
      print('Epoca:', epoca, '| Erro: ', sess.run(erro_soma))
      if erro_soma.eval() == 0.0:
        break

      W_final = sess.run(W)

Epoca: 1 | Erro:  3.0
Epoca: 2 | Erro:  3.0
Epoca: 3 | Erro:  3.0
Epoca: 4 | Erro:  2.0
Epoca: 5 | Erro:  2.0
Epoca: 6 | Erro:  2.0
Epoca: 7 | Erro:  2.0
Epoca: 8 | Erro:  0.0


In [93]:
# pesos finais, que a rede neural chegou
W_final

array([[1.],
       [1.]])

In [94]:
# Testar as classificacoes com a rede neural
camada_saida_teste = tf.compat.v1.matmul(X, W_final)
camada_saida_ativaca_teste = step(camada_saida_teste)
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(camada_saida_ativaca_teste))

# Os valores sao iguais aos valor da variavel y


[[0.]
 [1.]
 [1.]
 [1.]]


# Classificacao XOR

In [95]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [96]:
y = np.array([[1], [0], [0], [1]])
y

array([[1],
       [0],
       [0],
       [1]])

In [97]:
neuronios_entrada = 2
neuronios_oculta = 3
neuronios_saida = 1

In [102]:
# Criando pesos aleatorios para os neuronios ocultos e para as saídas
W = {
    'oculta': tf.Variable(tf.compat.v1.random_normal([neuronios_entrada, neuronios_oculta]), name="w_oculta"),
    'saida': tf.Variable(tf.compat.v1.random_normal([neuronios_oculta, neuronios_saida]), name = 'w_saida')
}

In [107]:
distribuicao = np.random.normal(size=500)


In [108]:
# Criando um bias
b = {
    "oculta": tf.Variable(tf.compat.v1.random_normal([neuronios_oculta]), name = "b_oculta"),
    "saida": tf.Variable(tf.compat.v1.random_normal([neuronios_saida]), name = "b_saida")
}

In [110]:
# Criando placeholders
xph = tf.compat.v1.placeholder(tf.float32, [4, neuronios_entrada], name = "xph")
yph = tf.compat.v1.placeholder(tf.float32, [4, neuronios_saida], name = "yph") # Valores reais

In [114]:
camada_oculta = tf.add(tf.matmul(xph, W["oculta"]), b["oculta"])
camada_oculta_ativacao = tf.sigmoid(camada_oculta)
camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W["saida"]), b["saida"])
camada_saida_ativacao = tf.sigmoid(camada_saida) # valores retornados pela rede

erro = tf.compat.v1.losses.mean_squared_error(yph, camada_saida_ativacao)
otimizador = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.3).minimize(erro)

In [116]:
# Visualizar os valores dos pesos iniciais
init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as sess:
  sess.run(init)

  for epocas in range(10000):
    erro_medio = 0.0
    _, custo = sess.run([otimizador, erro], feed_dict={xph: X, yph: y})
    erro_medio += custo / 4
    if epocas % 200 == 0:
      print("Epoca: ", epocas, "Erro: ", erro_medio)

  W_final, b_final = sess.run([W, b])


Epoca:  0 Erro:  0.06818442046642303
Epoca:  200 Erro:  0.06313850730657578
Epoca:  400 Erro:  0.06281116604804993
Epoca:  600 Erro:  0.06262829899787903
Epoca:  800 Erro:  0.06249741092324257
Epoca:  1000 Erro:  0.06236819550395012
Epoca:  1200 Erro:  0.062198422849178314
Epoca:  1400 Erro:  0.061935339123010635
Epoca:  1600 Erro:  0.06148974224925041
Epoca:  1800 Erro:  0.06067996472120285
Epoca:  2000 Erro:  0.05913693085312843
Epoca:  2200 Erro:  0.05628769472241402
Epoca:  2400 Erro:  0.051833152770996094
Epoca:  2600 Erro:  0.04664095863699913
Epoca:  2800 Erro:  0.04208662733435631
Epoca:  3000 Erro:  0.038071490824222565
Epoca:  3200 Erro:  0.03125399351119995
Epoca:  3400 Erro:  0.02118212915956974
Epoca:  3600 Erro:  0.013149505481123924
Epoca:  3800 Erro:  0.008439332246780396
Epoca:  4000 Erro:  0.005815575830638409
Epoca:  4200 Erro:  0.004279688000679016
Epoca:  4400 Erro:  0.003317093476653099
Epoca:  4600 Erro:  0.0026748015079647303
Epoca:  4800 Erro:  0.00222326256334

In [117]:
# Pesos ideias que a rede neural identificou
W_final

{'oculta': array([[ 3.042918 ,  6.1026473,  4.779469 ],
        [-5.5366387, -4.704968 ,  3.8201354]], dtype=float32),
 'saida': array([[-7.456425 ],
        [ 7.5277615],
        [-4.7046094]], dtype=float32)}

In [118]:
# Bias ideal qua rede neural identificou
b_final

{'oculta': array([-0.8476078 ,  2.252152  , -0.91708964], dtype=float32),
 'saida': array([0.5988993], dtype=float32)}

In [119]:
# Teste
camada_oculta_teste = tf.add(tf.matmul(xph, W_final["oculta"]), b_final["oculta"])
camada_oculta_ativacao_teste = tf.sigmoid(camada_oculta_teste)
camada_saida_teste = tf.add(tf.matmul(camada_oculta_ativacao_teste, W_final["saida"]), b_final["saida"])
camada_saida_ativacao_teste = tf.sigmoid(camada_saida_teste) # valores retornados pela rede

In [121]:

# Realizando apenas uma previsão, por isso nao informado o y
# O primeiro e ultimo valor estao bem proximo de 1 que é o correto da minha variavel y
with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(camada_saida_ativacao_teste, feed_dict={xph: X}))

[[0.9787608 ]
 [0.0363626 ]
 [0.03945385]
 [0.9515991 ]]
