<a href="https://colab.research.google.com/github/vinisouz4/TensorFlowStudy/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constantes

In [54]:
import tensorflow as tf

In [55]:
# Criando as constantes
valor1 = tf.constant(2)
valor2 = tf.constant(3)

In [56]:
# printando os valores das constantes
print(valor1)
print(valor2)

# Shape => é o tamanho ou o formato da constante, e está vazio porque é numero escalar

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [57]:
# Somando os valores das constantes
# Aqui ele gera um grafo
soma = valor1 + valor2

In [58]:
soma

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [59]:
texto1 = tf.constant('Texto 1 ')
texto2 = tf.constant('Texto 2')

In [60]:
texto1

<tf.Tensor: shape=(), dtype=string, numpy=b'Texto 1 '>

In [61]:
# Concatenar duas strings com o tensorflow
# b -> bites literal
concat = texto1 + texto2
concat

<tf.Tensor: shape=(), dtype=string, numpy=b'Texto 1 Texto 2'>

# Variaveis

In [62]:

# Sempre colocar o parametro *name* o nome da variavel para facilitar em projetos maiores
valor1 = tf.constant(15, name='valor1')
print(valor1)

tf.Tensor(15, shape=(), dtype=int32)


In [63]:
# Definindo variaveis no TensorFlow, no qual ele define como será o grafo, já com a criação de sessão
soma = tf.Variable(valor1 + 5, name="valor1")
soma

<tf.Variable 'valor1:0' shape=() dtype=int32, numpy=20>

In [64]:
# No retorno é mostrado que tem uma lista (vetor), no parametro shape me mostra que temos 3 itens dentro do meu vetor
vetor = tf.constant([5, 10, 15], name='vetor')
vetor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10, 15], dtype=int32)>

In [65]:
# Criar uma soma no qual pegue todos os meus valores do vetor e some por 5
soma = tf.Variable(vetor + 5, name='soma')
soma

<tf.Variable 'soma:0' shape=(3,) dtype=int32, numpy=array([10, 15, 20], dtype=int32)>

In [66]:
valor = tf.Variable(0, name='valor')

# Looping no qual ele pega um range e incrementa na minha variabel
for i in range(5):
  valor = valor + 1
  print(valor)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


# Adição de Vetores e Matrizes

In [67]:
a = tf.constant([9,8,7], name='a')
b = tf.constant([1,2,3], name='b')

In [68]:
# Vou fazer a soma dos itens da minha lista a com a minha lista b
soma = a + b
soma

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [69]:
# No parametro shape ele me mostra que temos duas colunas (duas listas) com 3 itens dentro delas
a1 = tf.constant([[1,2,3], [4,5,6]], name = 'a1')
a1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [70]:
a1.shape

TensorShape([2, 3])

In [71]:
b1 = tf.constant([[1,2,3], [4,5,6]], name="b1")
b1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [72]:
# O parametro .add é uma soma usando as prioridades do TensorFlow
soma = tf.add(a1, b1)
soma

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [73]:
soma.numpy()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [78]:
a2 = tf.constant([[1,2,3], [4,5,6]], name='a2')
b2 = tf.constant([[1], [2]], name='b2')
soma = tf.add(a2, b2)
soma

# with tf.compat.v1.Session() as sess:
#   print(sess.run(soma))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [6, 7, 8]], dtype=int32)>

# Multiplicações de Matrizes

In [79]:
a = tf.constant([[1,2], [3,4]], name='a')
b = tf.constant([[-1,3], [4,2]], name='b')

In [82]:
# Realizando a multiplicação entre matrizes entre A e B
multiplicacao = tf.matmul(a,b)
multiplicacao

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  7],
       [13, 17]], dtype=int32)>

In [83]:
multiplicacao2 = tf.matmul(b,a)
multiplicacao2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 10],
       [10, 16]], dtype=int32)>

In [84]:
a1 = tf.constant([[2,3], [0,1], [-1,4]])
b1 = tf.constant([[1,2,3], [-2,0,4]])
multiplicacao3 = tf.matmul(a1,b1)
multiplicacao3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[-4,  4, 18],
       [-2,  0,  4],
       [-9, -2, 13]], dtype=int32)>

# Produto Escalar

In [90]:
a = tf.constant([-1.0, 7.0, 5.0], name="entradas")
b = tf.constant([0.8, 0.1, 0.0], name="pesos")
multiplicacao = tf.multiply(a,b)
multiplicacao

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.8,  0.7,  0. ], dtype=float32)>

In [91]:
# Somar os valores da multiplicacao
somaa = tf.reduce_sum(multiplicacao)
somaa

<tf.Tensor: shape=(), dtype=float32, numpy=-0.10000002384185791>

# Placeholder (Tradução Literal: Espaço reservado)

In [95]:
# Desativo o eager que executa o o tensorflow na versão 1.x
tf.compat.v1.disable_eager_execution()

In [97]:
# Criando um placeholder, no qual será esperado um valor em tipo float, mas no Tensor 2.x é usado tf.constant
# O None eu deixo especificado que meu placeholder não tem um limite de tamanho, podendo ser vetores e matrizes de diversos tamanhos
p = tf.compat.v1.placeholder('float', None)

In [98]:
operacao  = p + 2

In [99]:
operacao

<tf.Tensor 'add_1:0' shape=<unknown> dtype=float32>

In [102]:
# Para o placeholder ser executado, eu preciso passar para ele os valores que eu desejo fazer as movimentações
# No caso eu preciso passar um dicionario com os valores que eu preciso que seja calculado
with tf.compat.v1.Session() as sess:
  resultado = sess.run(operacao, feed_dict={p: [1,2,3]})
  print(resultado)

[3. 4. 5.]


In [103]:
# Se eu crio um Placeholder especificando o tamanho do meu placeholder, eu tenho que passar o mesmo tamanho quando for para definir o valor do Placeholder
p1 = tf.compat.v1.placeholder('float', 1)
operacao1 = p1 + 2

with tf.compat.v1.Session() as sess:
  resultado = sess.run(operacao, feed_dict={p: [1]})
  print(resultado)

[3.]


In [105]:
# Passando uma matriz para placeholder com 5 colunas
p3 = tf.compat.v1.placeholder('float', [None, 5])
operacao3 = p3 * 5

In [106]:
with tf.compat.v1.Session() as sess:
  dados = [[1,2,3,4,5], [6,7,8,9,10]]
  resultado = sess.run(operacao3, feed_dict={p3: dados})

In [107]:
resultado

array([[ 5., 10., 15., 20., 25.],
       [30., 35., 40., 45., 50.]], dtype=float32)

# Grafos e Visualização com TensorBoard

- Bom usar os escopos para criar grupos e subgrupos quando possui diversos calculos

In [118]:
# Definindo escopos

with tf.compat.v1.name_scope('Operacoes'):
  with tf.compat.v1.name_scope('Escopo_A'):
    a = tf.add(2,2, name='add')
  with tf.compat.v1.name_scope('Escopo_B'):
    b = tf.multiply(a, 3, name='mult1')
    c = tf.multiply(b, a, name='mult2')

In [119]:
print(a)
print(b)
print(c)

Tensor("Operacoes/Escopo_A/add:0", shape=(), dtype=int32)
Tensor("Operacoes/Escopo_B/mult1:0", shape=(), dtype=int32)
Tensor("Operacoes/Escopo_B/mult2:0", shape=(), dtype=int32)


In [120]:
# Aqui eu reseto meu graph para eu conseguir gerar outros grafos
tf.compat.v1.reset_default_graph

<function tensorflow.python.framework.ops.reset_default_graph() -> None>

In [122]:
# Gerando o grafos que foi gerado nessa sessão
with tf.compat.v1.Session() as sess:
  writer = tf.compat.v1.summary.FileWriter('output', sess.graph) # Criado o arquivo do grafo gerado pelo TensorBoard
  print(sess.run(c))
  writer.close()

48
